import type {
  BillingEntry,
  Case,
  Client,
  Complaint,
  DashboardData,
  EvidenceItem,
  Filing,
  Fir,
  KnowledgeDoc,
  LegalNotification,
  ProviderConfig,
} from "../types";

export const mockCases: Case[] = [
  {
    id: "case-001",
    caseNumber: "WP(C) 482/2024",
    title: "Sharma vs State of Delhi",
    court: "Delhi High Court",
    bench: "Hon'ble Justice A. Mehta",
    clientId: "cli-001",
    clientName: "Rajesh Sharma",
    advocate: "Adv. Priya Nair",
    status: "active",
    stage: "arguments",
    nextHearing: "2026-07-19T10:30:00",
    filingDate: "2024-03-12",
    category: "Writ Petition",
    cnrs: "DLHC012024004821",
    priority: "high",
    lastOrder: "List for final arguments on 19.07.2026",
  },
  {
    id: "case-002",
    caseNumber: "CS(OS) 156/2023",
    title: "Meridian Infra vs Apex Builders",
    court: "Delhi High Court",
    bench: "Hon'ble Justice R. Kapoor",
    clientId: "cli-002",
    clientName: "Meridian Infra Pvt Ltd",
    advocate: "Adv. Vikram Singh",
    status: "pending",
    stage: "evidence",
    nextHearing: "2026-07-22T11:00:00",
    filingDate: "2023-08-05",
    category: "Civil Suit",
    priority: "medium",
    lastOrder: "Plaintiff to file affidavit of evidence",
  },
  {
    id: "case-003",
    caseNumber: "CRL.A 445/2025",
    title: "State vs Anil Kumar",
    court: "Supreme Court of India",
    bench: "Hon'ble Justice S. Bhat, Hon'ble Justice M. Shah",
    clientId: "cli-003",
    clientName: "Anil Kumar",
    advocate: "Adv. Priya Nair",
    status: "active",
    stage: "admission",
    nextHearing: "2026-07-25T10:30:00",
    filingDate: "2025-01-18",
    category: "Criminal Appeal",
    priority: "high",
  },
  {
    id: "case-004",
    caseNumber: "ARB.P 89/2024",
    title: "Nova Tech vs CloudServe LLP",
    court: "Delhi High Court",
    clientId: "cli-004",
    clientName: "Nova Tech Solutions",
    advocate: "Adv. Meera Joshi",
    status: "disposed",
    stage: "disposed",
    filingDate: "2024-06-20",
    category: "Arbitration",
    priority: "low",
    lastOrder: "Petition disposed as withdrawn",
  },
  {
    id: "case-005",
    caseNumber: "BAIL APP 234/2026",
    title: "Ravi Mehta — Regular Bail",
    court: "Sessions Court, Saket",
    clientId: "cli-005",
    clientName: "Ravi Mehta",
    advocate: "Adv. Vikram Singh",
    status: "active",
    stage: "arguments",
    nextHearing: "2026-07-19T14:00:00",
    filingDate: "2026-06-28",
    category: "Bail Application",
    priority: "high",
  },
];

export const mockComplaints: Complaint[] = [
  {
    id: "cmp-001",
    complaintNumber: "CMP/2026/0142",
    complainant: "Sunita Devi",
    respondent: "Unknown persons",
    subject: "Cyber fraud — UPI scam",
    policeStation: "Cyber Cell, Dwarka",
    district: "South West Delhi",
    status: "registered",
    registeredAt: "2026-07-10T09:00:00",
    category: "Cyber Crime",
    description: "Complainant lost ₹4.2L via fraudulent UPI links. Transaction IDs attached.",
    assignedOfficer: "SI Rajat Verma",
  },
  {
    id: "cmp-002",
    complaintNumber: "CMP/2026/0098",
    complainant: "Greenfield Housing Society",
    respondent: "Builder — Skyline Developers",
    subject: "Non-delivery of possession",
    policeStation: "Sector 18 PS, Noida",
    district: "Gautam Buddha Nagar",
    status: "under_inquiry",
    registeredAt: "2026-06-15T11:30:00",
    category: "Consumer / Property",
    description: "200+ allottees affected. RERA orders not complied with.",
    assignedOfficer: "Insp. Neha Gupta",
  },
  {
    id: "cmp-003",
    complaintNumber: "CMP/2025/0891",
    complainant: "Arjun Patel",
    subject: "Cheque bounce — Section 138",
    policeStation: "Karol Bagh PS",
    district: "Central Delhi",
    status: "converted_to_fir",
    registeredAt: "2025-11-20T10:00:00",
    category: "Economic Offence",
    firId: "fir-002",
    description: "Dishonoured cheque ₹18L. Legal notice served.",
  },
];

export const mockFirs: Fir[] = [
  {
    id: "fir-001",
    firNumber: "0126/2026",
    sections: ["420 IPC", "66D IT Act"],
    policeStation: "Cyber Cell, Dwarka",
    district: "South West Delhi",
    complainant: "Sunita Devi",
    status: "investigation",
    registeredAt: "2026-07-12T16:00:00",
    investigatingOfficer: "SI Rajat Verma",
    linkedComplaintId: "cmp-001",
    summary: "UPI fraud investigation — bank statements obtained.",
    bailStatus: "not_applicable",
  },
  {
    id: "fir-002",
    firNumber: "0891/2025",
    sections: ["138 NI Act"],
    policeStation: "Karol Bagh PS",
    district: "Central Delhi",
    complainant: "Arjun Patel",
    accused: "M/s Bright Traders",
    status: "chargesheet",
    registeredAt: "2025-12-01T14:00:00",
    investigatingOfficer: "Insp. Suresh Yadav",
    linkedComplaintId: "cmp-003",
    summary: "Chargesheet filed. Trial listed.",
    bailStatus: "granted",
    chargeSheet: {
      filedAt: "2026-03-15T10:00:00",
      referenceNumber: "CS/2026/0891",
      notes: "Trial court listed for July 2026.",
    },
  },
  {
    id: "fir-003",
    firNumber: "0045/2026",
    sections: ["302 IPC", "34 IPC"],
    policeStation: "Rohini Sector 11 PS",
    district: "North West Delhi",
    complainant: "State",
    accused: "Accused A & B",
    status: "investigation",
    registeredAt: "2026-05-08T08:00:00",
    investigatingOfficer: "ACP Ramesh Lal",
    summary: "Murder case — forensic reports pending.",
    bailStatus: "rejected",
  },
];

export const mockFilings: Filing[] = [
  {
    id: "fil-001",
    caseId: "case-001",
    caseNumber: "WP(C) 482/2024",
    title: "Written submissions — Final arguments",
    filingType: "reply",
    status: "filed",
    diaryNumber: "DLHC/2026/4821",
    courtFees: 500,
    createdAt: "2026-07-10T09:00:00",
  },
  {
    id: "fil-002",
    caseId: "case-002",
    caseNumber: "CS(OS) 156/2023",
    title: "Affidavit of evidence — Plaintiff",
    filingType: "affidavit",
    status: "checklist",
    createdAt: "2026-07-15T11:00:00",
  },
  {
    id: "fil-003",
    caseId: "case-005",
    caseNumber: "BAIL APP 234/2026",
    title: "Bail application with supporting documents",
    filingType: "application",
    status: "registered",
    diaryNumber: "SC/2026/234",
    createdAt: "2026-06-28T14:00:00",
  },
];

export const mockKnowledge: KnowledgeDoc[] = [
  {
    id: "kb-001",
    title: "Writ Petition — Template (Delhi HC)",
    category: "template",
    body: "Template for Article 226 writ petitions before Delhi High Court.",
    tags: ["writ", "delhi-hc"],
    bookmarked: true,
    createdAt: "2026-01-10T10:00:00",
  },
  {
    id: "kb-002",
    title: "Indian Penal Code — Section 420 Overview",
    category: "act",
    body: "Cheating and dishonestly inducing delivery of property.",
    tags: ["ipc", "420"],
    bookmarked: false,
    createdAt: "2026-02-05T10:00:00",
  },
  {
    id: "kb-003",
    title: "FIR Conversion SOP",
    category: "sop",
    body: "Standard operating procedure for complaint to FIR conversion.",
    tags: ["fir", "complaint"],
    bookmarked: true,
    createdAt: "2026-03-01T10:00:00",
  },
];

export const mockNotifications: LegalNotification[] = [
  {
    id: "notif-001",
    title: "Hearing today",
    message: "WP(C) 482/2024 listed at 10:30 AM — Court 3",
    type: "HEARING_SCHEDULED",
    read: false,
    createdAt: "2026-07-19T07:00:00",
    href: "/legal/calendar",
  },
  {
    id: "notif-002",
    title: "Complaint follow-up due",
    message: "CMP/2026/0098 requires follow-up today",
    type: "COMPLAINT_FOLLOW_UP_DUE",
    read: false,
    createdAt: "2026-07-19T08:00:00",
    href: "/legal/complaints/cmp-002",
  },
  {
    id: "notif-003",
    title: "Filing defect raised",
    message: "Registry objection on CS(OS) 156/2023 affidavit",
    type: "FILING_DEFECT",
    read: true,
    createdAt: "2026-07-18T16:00:00",
    href: "/legal/filing",
  },
];

export const mockClients: Client[] = [
  {
    id: "cli-001",
    name: "Rajesh Sharma",
    type: "individual",
    email: "rajesh.sharma@email.com",
    phone: "+91 98100 12345",
    city: "New Delhi",
    activeMatters: 2,
    totalBilled: 850000,
    joinedAt: "2023-01-15",
  },
  {
    id: "cli-002",
    name: "Meridian Infra Pvt Ltd",
    type: "corporate",
    email: "legal@meridianinfra.in",
    phone: "+91 11 4567 8900",
    city: "Gurgaon",
    activeMatters: 4,
    totalBilled: 4200000,
    joinedAt: "2022-06-01",
  },
  {
    id: "cli-003",
    name: "Anil Kumar",
    type: "individual",
    phone: "+91 98765 43210",
    city: "Patna",
    activeMatters: 1,
    totalBilled: 1250000,
    joinedAt: "2024-11-20",
  },
  {
    id: "cli-004",
    name: "Nova Tech Solutions",
    type: "corporate",
    email: "compliance@novatech.io",
    phone: "+91 80 2345 6789",
    city: "Bangalore",
    activeMatters: 3,
    totalBilled: 2100000,
    joinedAt: "2024-03-10",
  },
];

export const mockEvidence: EvidenceItem[] = [
  {
    id: "ev-001",
    caseId: "case-001",
    caseNumber: "WP(C) 482/2024",
    title: "Affidavit — Petitioner",
    type: "document",
    uploadedAt: "2026-07-01T10:00:00",
    hash: "sha256:a3f2…9c1d",
    size: "2.4 MB",
    status: "verified",
    uploadedBy: "Adv. Priya Nair",
  },
  {
    id: "ev-002",
    caseId: "case-002",
    caseNumber: "CS(OS) 156/2023",
    title: "Site photographs — Phase II",
    type: "photo",
    uploadedAt: "2026-06-28T15:30:00",
    hash: "sha256:b7e1…4f8a",
    size: "18.6 MB",
    status: "verified",
    uploadedBy: "Adv. Vikram Singh",
  },
  {
    id: "ev-003",
    caseId: "case-005",
    caseNumber: "BAIL APP 234/2026",
    title: "CCTV footage — Saket Metro",
    type: "video",
    uploadedAt: "2026-07-15T09:00:00",
    hash: "sha256:c9d3…2b7e",
    size: "156 MB",
    status: "pending",
    uploadedBy: "Adv. Vikram Singh",
  },
];

export const mockBilling: BillingEntry[] = [
  {
    id: "bill-001",
    clientId: "cli-002",
    clientName: "Meridian Infra Pvt Ltd",
    matterRef: "CS(OS) 156/2023",
    amount: 350000,
    status: "sent",
    dueDate: "2026-07-25",
    issuedAt: "2026-07-01",
  },
  {
    id: "bill-002",
    clientId: "cli-001",
    clientName: "Rajesh Sharma",
    matterRef: "WP(C) 482/2024",
    amount: 125000,
    status: "paid",
    dueDate: "2026-07-10",
    issuedAt: "2026-06-20",
  },
  {
    id: "bill-003",
    clientId: "cli-004",
    clientName: "Nova Tech Solutions",
    matterRef: "ARB.P 89/2024",
    amount: 280000,
    status: "overdue",
    dueDate: "2026-06-30",
    issuedAt: "2026-06-01",
  },
];

export const mockProviders: ProviderConfig[] = [
  {
    id: "ecourts",
    name: "eCourts Services",
    status: "degraded",
    lastSync: "2026-07-19T08:45:00",
    enabled: true,
    description: "CNR lookup, cause list, case status from eCourts portal.",
  },
  {
    id: "scc",
    name: "SCC Online",
    status: "connected",
    lastSync: "2026-07-19T09:12:00",
    enabled: true,
    description: "Case law research, citator, statute references.",
  },
  {
    id: "manupatra",
    name: "Manupatra",
    status: "not_configured",
    enabled: false,
    description: "Legal research database — API key required.",
  },
];

export const mockDashboard: DashboardData = {
  kpis: {
    activeMatters: 24,
    pendingMatters: 8,
    disposedThisMonth: 5,
    newClientsThisMonth: 3,
    pendingComplaints: 12,
    pendingFirs: 7,
    revenueThisMonth: 2850000,
    complianceOverdue: 4,
  },
  todaysHearings: [
    {
      id: "h-001",
      caseId: "case-001",
      caseNumber: "WP(C) 482/2024",
      title: "Sharma vs State of Delhi",
      court: "Delhi High Court",
      bench: "Court 3 — Justice A. Mehta",
      dateTime: "2026-07-19T10:30:00",
      type: "final",
      itemNumber: 42,
      advocate: "Adv. Priya Nair",
    },
    {
      id: "h-002",
      caseId: "case-005",
      caseNumber: "BAIL APP 234/2026",
      title: "Ravi Mehta — Regular Bail",
      court: "Sessions Court, Saket",
      bench: "Court 2",
      dateTime: "2026-07-19T14:00:00",
      type: "urgent",
      itemNumber: 8,
      advocate: "Adv. Vikram Singh",
    },
  ],
  upcomingHearings: [
    {
      id: "h-003",
      caseId: "case-002",
      caseNumber: "CS(OS) 156/2023",
      title: "Meridian Infra vs Apex Builders",
      court: "Delhi High Court",
      bench: "Court 7",
      dateTime: "2026-07-22T11:00:00",
      type: "regular",
      itemNumber: 15,
      advocate: "Adv. Vikram Singh",
    },
    {
      id: "h-004",
      caseId: "case-003",
      caseNumber: "CRL.A 445/2025",
      title: "State vs Anil Kumar",
      court: "Supreme Court",
      bench: "Court 2",
      dateTime: "2026-07-25T10:30:00",
      type: "regular",
      advocate: "Adv. Priya Nair",
    },
  ],
  causeList: [
    {
      id: "cl-001",
      itemNumber: 42,
      caseNumber: "WP(C) 482/2024",
      title: "Sharma vs State of Delhi",
      purpose: "Final Arguments",
      court: "Delhi HC — Court 3",
      bench: "Justice A. Mehta",
      advocate: "Adv. Priya Nair",
      status: "listed",
    },
    {
      id: "cl-002",
      itemNumber: 43,
      caseNumber: "CM APPL 891/2024",
      title: "Interim relief — Stay",
      purpose: "Mentioning",
      court: "Delhi HC — Court 3",
      bench: "Justice A. Mehta",
      advocate: "Adv. Meera Joshi",
      status: "listed",
    },
    {
      id: "cl-003",
      itemNumber: 44,
      caseNumber: "LPA 234/2025",
      title: "Tax assessment challenge",
      purpose: "Admission",
      court: "Delhi HC — Court 3",
      bench: "Justice A. Mehta",
      advocate: "Adv. Vikram Singh",
      status: "adjourned",
    },
  ],
  pendingMatters: mockCases.filter((c) => c.status === "pending" || c.status === "active"),
  disposedMatters: mockCases.filter((c) => c.status === "disposed"),
  newClients: mockClients.slice(0, 2),
  caseAlerts: [
    {
      id: "alert-001",
      caseId: "case-001",
      caseNumber: "WP(C) 482/2024",
      message: "Counter-affidavit filed by respondent — review before hearing",
      severity: "warning",
      createdAt: "2026-07-18T16:00:00",
    },
    {
      id: "alert-002",
      caseId: "case-005",
      caseNumber: "BAIL APP 234/2026",
      message: "Prosecution objection uploaded — urgent review",
      severity: "critical",
      createdAt: "2026-07-19T07:30:00",
    },
  ],
  courtNotices: [
    {
      id: "cn-001",
      title: "Summons — Witness examination",
      court: "Delhi HC",
      issuedAt: "2026-07-15",
      deadline: "2026-07-22",
      type: "summons",
      matterRef: "CS(OS) 156/2023",
    },
    {
      id: "cn-002",
      title: "Office circular — E-filing maintenance",
      court: "Supreme Court",
      issuedAt: "2026-07-17",
      type: "circular",
    },
  ],
  recentOrders: [
    {
      id: "ord-001",
      caseNumber: "WP(C) 482/2024",
      title: "List for final arguments",
      date: "2026-07-12",
      court: "Delhi HC",
    },
    {
      id: "ord-002",
      caseNumber: "CRL.MC 567/2026",
      title: "Notice issued to respondent",
      date: "2026-07-10",
      court: "Delhi HC",
    },
  ],
  latestJudgments: [
    {
      id: "jud-001",
      citation: "(2026) 4 SCC 112",
      title: "State of Maharashtra vs Accused — Bail jurisprudence",
      court: "SC",
      bench: "3-Judge Bench",
      date: "2026-07-08",
      summary: "Expanded scope of anticipatory bail in economic offences.",
    },
    {
      id: "jud-002",
      citation: "2026 SCC OnLine Del 4521",
      title: "Builder-buyer disputes — RERA interplay",
      court: "HC",
      bench: "Division Bench",
      date: "2026-07-05",
      summary: "Concurrent jurisdiction of RERA and consumer forums clarified.",
    },
  ],
  legalNews: [
    {
      id: "news-001",
      title: "Supreme Court collegium recommends 3 new judges",
      source: "Bar & Bench",
      publishedAt: "2026-07-18",
      category: "Judiciary",
    },
    {
      id: "news-002",
      title: "New IT Rules amendments notified",
      source: "LiveLaw",
      publishedAt: "2026-07-17",
      category: "Legislation",
    },
  ],
  hcScUpdates: [
    {
      id: "upd-001",
      title: "Delhi HC: Guidelines on virtual hearings extended",
      source: "Delhi HC Registry",
      publishedAt: "2026-07-16",
      category: "HC Update",
    },
    {
      id: "upd-002",
      title: "SC: Constitution Bench to hear Article 370 matters",
      source: "SC Registry",
      publishedAt: "2026-07-14",
      category: "SC Update",
    },
  ],
  aiInsights: [
    {
      id: "ai-001",
      title: "Strong precedents for WP(C) 482/2024",
      summary: "3 recent Delhi HC judgments support your Article 14 argument. Consider citing 2025 SCC OnLine Del 3890.",
      type: "research",
      priority: "medium",
      relatedCaseId: "case-001",
    },
    {
      id: "ai-002",
      title: "Compliance deadline approaching",
      summary: "GST filing for Meridian Infra due in 5 days. Linked to CS(OS) 156/2023 billing.",
      type: "compliance",
      priority: "high",
    },
  ],
  pendingCompliance: [
    {
      id: "comp-001",
      title: "Affidavit of service — WP(C) 482/2024",
      dueDate: "2026-07-20",
      status: "pending",
      category: "Filing",
      matterRef: "WP(C) 482/2024",
    },
    {
      id: "comp-002",
      title: "GST return — Q1 FY26",
      dueDate: "2026-07-15",
      status: "overdue",
      category: "Tax",
      matterRef: "Meridian Infra",
    },
  ],
  complaints: mockComplaints,
  pendingFirs: mockFirs.filter((f) => f.status !== "closed"),
  calendarEvents: [
    { id: "cal-001", title: "WP(C) 482/2024 — Final Arguments", date: "2026-07-19", type: "hearing", court: "Delhi HC" },
    { id: "cal-002", title: "Client meeting — Meridian Infra", date: "2026-07-21", type: "meeting" },
    { id: "cal-003", title: "CS(OS) 156/2023 — Evidence", date: "2026-07-22", type: "hearing", court: "Delhi HC" },
  ],
  revenueAnalytics: [
    { month: "Feb", revenue: 1800000, billed: 2100000 },
    { month: "Mar", revenue: 2200000, billed: 2400000 },
    { month: "Apr", revenue: 1950000, billed: 2300000 },
    { month: "May", revenue: 2500000, billed: 2700000 },
    { month: "Jun", revenue: 2100000, billed: 2600000 },
    { month: "Jul", revenue: 2850000, billed: 3100000 },
  ],
  practiceAnalytics: [
    { category: "Writ Petitions", count: 8 },
    { category: "Civil Suits", count: 6 },
    { category: "Criminal", count: 5 },
    { category: "Arbitration", count: 3 },
    { category: "Corporate", count: 2 },
  ],
};

export function getMockCaseById(id: string): Case | undefined {
  return mockCases.find((c) => c.id === id);
}

export function getMockComplaintById(id: string): Complaint | undefined {
  return mockComplaints.find((c) => c.id === id);
}

export function getMockFirById(id: string): Fir | undefined {
  return mockFirs.find((f) => f.id === id);
}

export function getMockFilingById(id: string): Filing | undefined {
  return mockFilings.find((f) => f.id === id);
}

export const mockHearings = [
  ...mockDashboard.todaysHearings,
  ...mockDashboard.upcomingHearings,
];
